[options]
admin_passwd = $pbkdf2-sha512$600000$yPm/d24NAQCAkFKKUSolxA$8zS6DthtU066V5zO5d2ATBhD6OJDGRcbnkCnrgQyv0B0J76ntY9ybEQDkpK.6.a7xrCyiVZknKDAT0ihQ/A4RA
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
workers = 0
max_cron_threads = 0
limit_memory_soft = 0
limit_memory_hard = 0
limit_time_cpu = 0
limit_time_real = 0

